/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as PanelAdminRouteImport } from './routes/panel-admin'
import { Route as PanelAdminLoginRouteImport } from './routes/panel-admin-login'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ExamSlugIndexRouteImport } from './routes/exam/$slug/index'
import { Route as ExamSlugInstructionsRouteImport } from './routes/exam/$slug/instructions'
import { Route as ExamSlugStartRouteImport } from './routes/exam/$slug/start'
import { Route as ExamSlugSubmittedRouteImport } from './routes/exam/$slug/submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/panel-admin',
  path: '/panel-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminLoginRoute = PanelAdminLoginRouteImport.update({
  id: '/panel-admin-login',
  path: '/panel-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSlugIndexRoute = ExamSlugIndexRouteImport.update({
  id: '/exam/$slug/',
  path: '/exam/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSlugInstructionsRoute = ExamSlugInstructionsRouteImport.update({
  id: '/exam/$slug/instructions',
  path: '/exam/$slug/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSlugStartRoute = ExamSlugStartRouteImport.update({
  id: '/exam/$slug/start',
  path: '/exam/$slug/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSlugSubmittedRoute = ExamSlugSubmittedRouteImport.update({
  id: '/exam/$slug/submitted',
  path: '/exam/$slug/submitted',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/panel-admin': typeof PanelAdminRoute
  '/panel-admin-login': typeof PanelAdminLoginRoute
  '/submitted': typeof SubmittedRoute
  '/exam/': typeof ExamIndexRoute
  '/exam/$slug/instructions': typeof ExamSlugInstructionsRoute
  '/exam/$slug/start': typeof ExamSlugStartRoute
  '/exam/$slug/submitted': typeof ExamSlugSubmittedRoute
  '/exam/$slug/': typeof ExamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/panel-admin': typeof PanelAdminRoute
  '/panel-admin-login': typeof PanelAdminLoginRoute
  '/submitted': typeof SubmittedRoute
  '/exam': typeof ExamIndexRoute
  '/exam/$slug/instructions': typeof ExamSlugInstructionsRoute
  '/exam/$slug/start': typeof ExamSlugStartRoute
  '/exam/$slug/submitted': typeof ExamSlugSubmittedRoute
  '/exam/$slug': typeof ExamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/panel-admin': typeof PanelAdminRoute
  '/panel-admin-login': typeof PanelAdminLoginRoute
  '/submitted': typeof SubmittedRoute
  '/exam/': typeof ExamIndexRoute
  '/exam/$slug/instructions': typeof ExamSlugInstructionsRoute
  '/exam/$slug/start': typeof ExamSlugStartRoute
  '/exam/$slug/submitted': typeof ExamSlugSubmittedRoute
  '/exam/$slug/': typeof ExamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizer'
    | '/panel-admin'
    | '/panel-admin-login'
    | '/submitted'
    | '/exam/'
    | '/exam/$slug/instructions'
    | '/exam/$slug/start'
    | '/exam/$slug/submitted'
    | '/exam/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizer'
    | '/panel-admin'
    | '/panel-admin-login'
    | '/submitted'
    | '/exam'
    | '/exam/$slug/instructions'
    | '/exam/$slug/start'
    | '/exam/$slug/submitted'
    | '/exam/$slug'
  id:
    | '__root__'
    | '/'
    | '/organizer'
    | '/panel-admin'
    | '/panel-admin-login'
    | '/submitted'
    | '/exam/'
    | '/exam/$slug/instructions'
    | '/exam/$slug/start'
    | '/exam/$slug/submitted'
    | '/exam/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRoute: typeof OrganizerRoute
  PanelAdminRoute: typeof PanelAdminRoute
  PanelAdminLoginRoute: typeof PanelAdminLoginRoute
  SubmittedRoute: typeof SubmittedRoute
  ExamIndexRoute: typeof ExamIndexRoute
  ExamSlugInstructionsRoute: typeof ExamSlugInstructionsRoute
  ExamSlugStartRoute: typeof ExamSlugStartRoute
  ExamSlugSubmittedRoute: typeof ExamSlugSubmittedRoute
  ExamSlugIndexRoute: typeof ExamSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-admin': {
      id: '/panel-admin'
      path: '/panel-admin'
      fullPath: '/panel-admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-admin-login': {
      id: '/panel-admin-login'
      path: '/panel-admin-login'
      fullPath: '/panel-admin-login'
      preLoaderRoute: typeof PanelAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$slug/': {
      id: '/exam/$slug/'
      path: '/exam/$slug'
      fullPath: '/exam/$slug/'
      preLoaderRoute: typeof ExamSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$slug/instructions': {
      id: '/exam/$slug/instructions'
      path: '/exam/$slug/instructions'
      fullPath: '/exam/$slug/instructions'
      preLoaderRoute: typeof ExamSlugInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$slug/start': {
      id: '/exam/$slug/start'
      path: '/exam/$slug/start'
      fullPath: '/exam/$slug/start'
      preLoaderRoute: typeof ExamSlugStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$slug/submitted': {
      id: '/exam/$slug/submitted'
      path: '/exam/$slug/submitted'
      fullPath: '/exam/$slug/submitted'
      preLoaderRoute: typeof ExamSlugSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRoute: OrganizerRoute,
  PanelAdminRoute: PanelAdminRoute,
  PanelAdminLoginRoute: PanelAdminLoginRoute,
  SubmittedRoute: SubmittedRoute,
  ExamIndexRoute: ExamIndexRoute,
  ExamSlugInstructionsRoute: ExamSlugInstructionsRoute,
  ExamSlugStartRoute: ExamSlugStartRoute,
  ExamSlugSubmittedRoute: ExamSlugSubmittedRoute,
  ExamSlugIndexRoute: ExamSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
